/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StopWatch {
    }
    interface TimerDisplay {
        "time": number;
    }
}
declare global {
    interface HTMLStopWatchElement extends Components.StopWatch, HTMLStencilElement {
    }
    var HTMLStopWatchElement: {
        prototype: HTMLStopWatchElement;
        new (): HTMLStopWatchElement;
    };
    interface HTMLTimerDisplayElement extends Components.TimerDisplay, HTMLStencilElement {
    }
    var HTMLTimerDisplayElement: {
        prototype: HTMLTimerDisplayElement;
        new (): HTMLTimerDisplayElement;
    };
    interface HTMLElementTagNameMap {
        "stop-watch": HTMLStopWatchElement;
        "timer-display": HTMLTimerDisplayElement;
    }
}
declare namespace LocalJSX {
    interface StopWatch {
    }
    interface TimerDisplay {
        "time": number;
    }
    interface IntrinsicElements {
        "stop-watch": StopWatch;
        "timer-display": TimerDisplay;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stop-watch": LocalJSX.StopWatch & JSXBase.HTMLAttributes<HTMLStopWatchElement>;
            "timer-display": LocalJSX.TimerDisplay & JSXBase.HTMLAttributes<HTMLTimerDisplayElement>;
        }
    }
}
