/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ApiVersion {
    }
}
declare global {
    interface HTMLApiVersionElement extends Components.ApiVersion, HTMLStencilElement {
    }
    var HTMLApiVersionElement: {
        prototype: HTMLApiVersionElement;
        new (): HTMLApiVersionElement;
    };
    interface HTMLElementTagNameMap {
        "api-version": HTMLApiVersionElement;
    }
}
declare namespace LocalJSX {
    interface ApiVersion {
    }
    interface IntrinsicElements {
        "api-version": ApiVersion;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "api-version": LocalJSX.ApiVersion & JSXBase.HTMLAttributes<HTMLApiVersionElement>;
        }
    }
}
